language: "node_js"
node_js:
  - "node"
services:
  - postgresql
cache:
  directories:
  - node_modules
before_script:
  - psql -c 'create database sagetest;' -U postgres
after_success:
  - yarn run test-with-coverage
